services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - laravel_app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  php:
    build:
      context: ../laravel-app
      dockerfile: ../docker/php/Dockerfile
    volumes:
      - laravel_app:/var/www/html
      - ./php/entrypoint.sh:/entrypoint.sh
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
      - DB_CONNECTION=mysql
      - DB_PORT=3306
    networks:
      - laravel-network
    entrypoint: ["/entrypoint.sh", "php-fpm"]

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mariadb
    networks:
      - laravel-network

volumes:
  mariadb_data:
  laravel_app:

networks:
  laravel-network:
    driver: bridge