version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8085:80"
      - "8443:443"
    volumes:
      - ../laravel-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel-network

  php:
    build:
      context: ./php
      dockerfile: Dockerfile.local
    volumes:
      - ../laravel-app:/var/www/html
    depends_on:
      - mariadb
    environment:
      - DB_HOST=mariadb
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    networks:
      - laravel-network

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - laravel-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8086:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - mariadb
    networks:
      - laravel-network

volumes:
  mariadb_data:

networks:
  laravel-network:
    driver: bridge